# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=500)),
                ('content_type', models.IntegerField(default=0)),
            ],
        ),
    ]
