# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
