# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
