# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20171213_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('open_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
