# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20171213_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_pinyin',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
