# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_person_name_pinyin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='is_done',
            new_name='has_star',
        ),
    ]
